modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory (24 is current forge version)
[[mods]] #mandatory
	modId="customoregen" #mandatory
	version="${version}" #mandatory
	displayName="Custom Ore Gen" #mandatory
	authors="Lawremi" #optional
	description='''
	Allows for complete customization of ore generation
	'''
	[[dependencies.customoregen]] #optional
	    modId="forge" #mandatory
	    mandatory=true #mandatory
	    versionRange="[25,)" #mandatory
	    ordering="NONE"
	    side="BOTH"
	[[dependencies.customoregen]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.14.4,)"
	    ordering="NONE"
	    side="BOTH"